sudo: required
dist: xenial
language: python
python:
  - 3.7
services:
  - docker

branches:
  only:
    - master
    - stable

env:
  global:
    - DOCKER_IMAGE=oggm/r2d
    - DOCKERHUB_USER=oggmci
    - secure: bBZQGS+zK4GRdDApUTUuvSQujp0R/xwNc+zooknD4voun5dPd39yKLQqT7KiLSJBiDfsX+FenXOaWa+mCR5V8KERwE9Q08joYiJu1BE74kV+7nFm8clfldsTcFAG0aeVbI3ys6rL92lBiOvgHg0Rx2ewsAefjhL1slmWmCoDzDUPOe8NuFKvdpUoW3D6DYfOii6h2E7VR4Vaqdju+GK/j0VLHbWN7pW8HN4TcnQPcq5ppOX4ZMZCITr4Pn4zLjdO67WDmuntzPWCrskSeAcRbEaKSxfZKiJK11EqWlKmTT2FtjTGMWOobI0N40472CzkXeL83AqH2BMk5tOZVKqonQIAutUzC4tnD7vJTY6dODfa7Meop9NqF/c+q3v9Ik9YiuEZUOn0+TDgIo6pXS0dhCM62NSw8pq8oBseV7srV92cm5Ae9Nk/7+uMWzKoRC4Liw2XZ0/6bTX6ScrEgM7Bq+iP8gmxssy3C/vfQZ+9+OeXtjDB8DW5Fr+t/z/uIrraxn4we3ja/AO//7ahePB6RrgR4SYICMA2GWcPpAlj2spvwQY541fHTd+2N+YvUQz3dqIudK5d5pS5rv7Lx65n4wYD6KqDVo1arFlFsvBFIzQafDP1agKacOq2gDoS7VGvdct9xIwfqpGMZ/5oESCrK/ARNsrjrDUtuWD/1ptEKuM=

install:
  - echo "${DOCKERHUB_PASS}" | docker login -u "${DOCKERHUB_USER}" --password-stdin || exit -1
  - pip3 install --upgrade pip setuptools
  - pip3 install --upgrade jupyter-repo2docker

script:
  - docker pull "${DOCKER_IMAGE}:stable" && CACHE_LINE="--cache-from '${DOCKER_IMAGE}:stable'" || CACHE_LINE=""
  - jupyter-repo2docker $CACHE_LINE --debug --user-name jovyan --user-id 1000 --no-run --image-name "${DOCKER_IMAGE}:stable" . || exit -1
  - docker run --rm "${DOCKER_IMAGE}:stable" pytest --pyargs salem || exit -1
  - docker run --rm "${DOCKER_IMAGE}:stable" pytest --pyargs oggm || exit -1

after_success:
  - docker tag "${DOCKER_IMAGE}:stable"
  - docker push "${DOCKER_IMAGE}:stable"

