name: oggm
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyter
  - jupyterlab
  - jupyterhub
  - bokeh
  - nbserverproxy
  - ipywidgets
  - graphviz
  - numpy=1.16.5
  - scipy=1.4.1
  - pandas=0.25.3
  - shapely
  - matplotlib
  - Pillow
  - netcdf4=1.5.3
  - scikit-image
  - scikit-learn
  - configobj
  - xarray
  - pytest
  - dask
  - bottleneck
  - pyproj=2.2.2
  - cartopy=0.17.0
  - geopandas=0.7.0
  - rasterio=1.1.2
  - pyviz_comms
  - bokeh
  - param
  - holoviews
  - hvplot
  - geoviews
  - panel
  - parambokeh
  - datashader
  - descartes
  - seaborn
  - ipympl
  - pytables=3.6.1
  - pip
  - pip:
    - joblib
    - progressbar2
    - motionless
    - nbgitpuller
    - git+https://github.com/fmaussion/salem.git
    - git+https://github.com/OGGM/oggm.git
    - git+https://github.com/OGGM/oggm-edu.git
    - git+https://github.com/GLIMS-RGI/rgitools
    - git+https://github.com/retostauffer/python-colorspace
    - git+https://github.com/OGGM/pytest-mpl

